runtime: python27
api_version: 1
threadsafe: true
service: escape

handlers:
  - url: /resources
    static_dir: resources/

  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest

  - name: webapp2
    version: "2.5.2"
